-- ============================================================
-- Migration 004 - Ball Python morphs (Co-dominant & Dominant)
-- ============================================================

-- ── CO-DOMINANT MORPHS ───────────────────────────────────────
-- These have a visual het form AND a super/homozygous form
INSERT OR IGNORE INTO morphs (id, species_id, name, gene_symbol, category, inheritance_type, super_form_name, has_health_concern, health_concern_desc, description, also_known_as, discovered_year, sort_order) VALUES

-- Foundational co-doms
('bp_pastel',        'ball_python', 'Pastel',           'pst',  'Co-dominant', 'co_dominant', 'Super Pastel',     0, NULL, 'Brightens yellow pigment and reduces pattern. One of the most common and versatile morphs. Super pastel is near-white with yellow blush.', NULL, 1997, 10),
('bp_spider',        'ball_python', 'Spider',           'sp',   'Co-dominant', 'co_dominant', 'Super Spider',     1, 'Neurological wobble - head tremor and balance issues. Severity varies. Super spider shows severe wobble. Controversial morph.', 'The most visually striking basic morph. Thin, web-like pattern with white belly. IMPORTANT: Carries neurological wobble. Super form is not recommended.', 'Woma Pattern (incorrect)', 1999, 20),
('bp_lesser',        'ball_python', 'Lesser',           'les',  'Co-dominant', 'co_dominant', 'Butter',           0, NULL, 'Brightens and cleans the pattern. Super form (Butter) is a pale yellow animal. Essential component in the BEL complex.', 'Lesser Platinum', 2001, 30),
('bp_mojave',        'ball_python', 'Mojave',           'moj',  'Co-dominant', 'co_dominant', 'Super Mojave',     0, NULL, 'Reduces and brightens pattern. Clean sides. Super Mojave is a white animal with blue/grey eyes - part of the BEL complex.', NULL, 2000, 40),
('bp_phantom',       'ball_python', 'Phantom',          'phn',  'Co-dominant', 'co_dominant', 'Super Phantom',    0, NULL, 'Reduces pattern and brightens yellows. Super Phantom is part of the BEL complex producing white animals.', NULL, 2005, 50),
('bp_mystic',        'ball_python', 'Mystic',           'mys',  'Co-dominant', 'co_dominant', 'Super Mystic',     0, NULL, 'Similar to Phantom. Part of the BEL complex. Super Mystic produces a white animal with dark eyes.', 'Mistique', 2006, 55),
('bp_butter',        'ball_python', 'Butter',           'but2', 'Co-dominant', 'co_dominant', 'Super Butter',     0, NULL, 'The super form of Lesser. Pale yellow, clean animal. Also used to describe the super form of some combos.', NULL, 2001, 58),
('bp_het_russo',     'ball_python', 'Het Russo (Dominant line)', 'hru','Co-dominant','co_dominant','Super Russo', 0, NULL, 'Pattern reducing co-dominant. Different from the recessive Russo gene.', NULL, 2007, 60),
('bp_yellow_belly',  'ball_python', 'Yellow Belly',     'yb',   'Co-dominant', 'co_dominant', 'Ivory',            0, NULL, 'Subtle in isolation - slightly cleaner sides and yellow belly. Super Yellow Belly (Ivory) is a stunning white/cream animal with yellow sides.', 'YB', 2000, 70),
('bp_gravel',        'ball_python', 'Gravel',           'grv',  'Co-dominant', 'co_dominant', 'Super Gravel',     0, NULL, 'Reduces pattern and alters colouration. Allelic to Yellow Belly. Super form is similar to Ivory.', NULL, 2009, 75),
('bp_asphalt',       'ball_python', 'Asphalt',          'asp',  'Co-dominant', 'co_dominant', 'Super Asphalt',    0, NULL, 'Another Yellow Belly allele. Dark, clean appearance. Allelic series with YB and Gravel.', NULL, 2011, 78),
('bp_orange_dream',  'ball_python', 'Orange Dream',     'od',   'Co-dominant', 'co_dominant', 'Super Orange Dream', 0, NULL, 'Vivid orange pattern enhancement. Super OD is an intensely orange animal. Stacks beautifully with most morphs.', 'OD', 2004, 80),
('bp_enchi',         'ball_python', 'Enchi',            'enc',  'Co-dominant', 'co_dominant', 'Super Enchi',      0, NULL, 'Brightens and saturates yellow/orange tones. Super Enchi is intensely coloured. Stacks very well.', 'Enchilada', 2003, 90),
('bp_pinstripe',     'ball_python', 'Pinstripe',        'pin',  'Co-dominant', 'co_dominant', 'Super Pinstripe',  0, NULL, 'Reduces lateral pattern to a thin pinstripe. Cleaner dorsal. Super Pinstripe is nearly patternless with a dorsal line.', 'Pin', 2001, 100),
('bp_woma',          'ball_python', 'Woma',             'wom',  'Co-dominant', 'co_dominant', 'Super Woma',       0, NULL, 'Banded pattern with faded sides. Resembles Woma python patterning. Super Woma has extreme pattern reduction.', 'Collision', 2001, 110),
('bp_fire',          'ball_python', 'Fire',             'fir',  'Co-dominant', 'co_dominant', 'Black Eyed Leucistic', 0, NULL, 'Subtle brightening in isolation. Super Fire (Black Eyed Leucistic / BEL) is a pure white snake with black eyes. Part of the BEL complex.', NULL, 2003, 120),
('bp_vanilla_cod',   'ball_python', 'Vanilla (Co-dom line)', 'van2','Co-dominant','co_dominant','Super Vanilla',  0, NULL, 'Co-dominant line of Vanilla. Brightens and cleans animals. Super is a very pale, clean animal.', NULL, 2009, 125),
('bp_leopard_cod',   'ball_python', 'Leopard (Co-dom line)','lep2','Co-dominant','co_dominant','Super Leopard',   0, NULL, 'Co-dominant line producing leopard-like spotting. Different gene from recessive Leopard.', NULL, 2007, 130),
('bp_spotnose',      'ball_python', 'Spotnose',         'sno',  'Co-dominant', 'co_dominant', 'Super Spotnose',   0, NULL, 'Produces a distinctive spotted nose pattern and reduced lateral pattern. Super Spotnose is nearly patternless.', NULL, 2003, 140),
('bp_blackhead',     'ball_python', 'Blackhead',        'bkh',  'Co-dominant', 'co_dominant', 'Super Blackhead',  0, NULL, 'Darkens the head and increases overall dark pigmentation. Super Blackhead is a dramatically dark, nearly black snake.', NULL, 2002, 150),
('bp_calico',        'ball_python', 'Calico',           'cal',  'Co-dominant', 'co_dominant', 'Super Calico',     0, NULL, 'Reduces pattern and creates splotchy, calico-cat-like markings. Super Calico is nearly all white.', NULL, 2006, 160),
('bp_cinnamon',      'ball_python', 'Cinnamon',         'cin',  'Co-dominant', 'co_dominant', 'Black Pastel',     0, NULL, 'Darkens the animal and alters pattern. Super Cinnamon (Black Pastel) is the darkest naturally occurring ball python, near-black.', NULL, 2002, 170),
('bp_black_pastel',  'ball_python', 'Black Pastel',     'bkp',  'Co-dominant', 'co_dominant', 'Super Black Pastel', 0, NULL, 'The super form of Cinnamon. Also produced as super Black Pastel (separate line from Cinnamon). Very dark animal.', NULL, 2002, 175),
('bp_het_clown_cod', 'ball_python', 'Clown (Co-dominant line)', 'clc','Co-dominant','co_dominant','Super Clown', 0, NULL, 'A separate co-dominant version of the clown pattern. Rare.', NULL, 2012, 178),
('bp_banana',        'ball_python', 'Banana',           'ban',  'Co-dominant', 'co_dominant', 'Super Banana',     0, NULL, 'Vivid yellow/banana coloration with pink/lavender undertones. Super Banana is intensely coloured. Females pass banana more frequently.', 'Coral Glow', 2003, 180),
('bp_coral_glow',    'ball_python', 'Coral Glow',       'cg',   'Co-dominant', 'co_dominant', 'Super Coral Glow', 0, NULL, 'Allelic to Banana. Warm coral-orange tones with lavender highlights. Produces Banana-like offspring when combined.', NULL, 2006, 185),
('bp_champagne',     'ball_python', 'Champagne',        'cha',  'Co-dominant', 'co_dominant', 'Super Champagne',  0, NULL, 'Reduces pattern significantly. Bubbly, champagne-like pattern appearance. Super Champagne is nearly patternless and pale.', NULL, 2005, 190),
('bp_tornado',       'ball_python', 'Tornado',          'tor',  'Co-dominant', 'co_dominant', 'Super Tornado',    0, NULL, 'Creates swirling, tornado-like pattern disruption. Interesting pattern variant.', NULL, 2010, 200),
('bp_mocha',         'ball_python', 'Mocha',            'moc2', 'Co-dominant', 'co_dominant', 'Super Mocha',      0, NULL, 'Rich brown coloration. BEL complex member. Super Mocha produces white animals with black eyes.', NULL, 2009, 210),
('bp_russo_cod',     'ball_python', 'Russo (Co-dom)',   'rco',  'Co-dominant', 'co_dominant', 'Super Russo',      0, NULL, 'Co-dominant Russo. Pattern reducer. Super form is pale and clean.', NULL, 2010, 215),
('bp_special',       'ball_python', 'Special',          'spe',  'Co-dominant', 'co_dominant', 'Super Special',    0, NULL, 'BEL complex allele. Super Special produces a white snake with dark eyes.', NULL, 2007, 220),
('bp_fader',         'ball_python', 'Fader',            'fad',  'Co-dominant', 'co_dominant', 'Super Fader',      0, NULL, 'Fades and lightens the overall pattern. Super Fader is very pale.', NULL, 2011, 225),
('bp_sulfur',        'ball_python', 'Sulfur',           'suf',  'Co-dominant', 'co_dominant', 'Super Sulfur',     0, NULL, 'Vivid yellow-green coloration. Related to the Orange Dream series.', NULL, 2012, 230),
('bp_heat',          'ball_python', 'Heat',             'hea',  'Co-dominant', 'co_dominant', 'Super Heat',       0, NULL, 'Warm colour intensifier. Super Heat enhances the orange/yellow tones dramatically.', NULL, 2013, 235),
('bp_ghi',           'ball_python', 'GHI',              'ghi',  'Co-dominant', 'co_dominant', 'Super GHI',        0, NULL, 'Gotta Have It. Darkens pattern, ink-black markings. Super GHI is extremely dark with vivid contrast.', 'Gotta Have It', 2007, 240),
('bp_lucifer',       'ball_python', 'Lucifer',          'luc',  'Co-dominant', 'co_dominant', 'Super Lucifer',    0, NULL, 'Dark and dramatic pattern alteration. Bold black markings.', NULL, 2012, 245),
('bp_highway_cod',   'ball_python', 'Highway (Co-dom)', 'hwc',  'Co-dominant', 'co_dominant', 'Super Highway',    0, NULL, 'Co-dominant line producing the highway pattern. Lateral stripe appearance.', NULL, 2012, 250),
('bp_bumblebee_gene','ball_python', 'Bumblebee (genetic)','bbg', 'Co-dominant', 'co_dominant', 'Super Bumblebee', 1, 'May carry spider wobble if it contains the spider gene.', 'A genetic component producing bumblebee-like colouration.', NULL, 2010, 255),
('bp_specter_cod',   'ball_python', 'Specter (Co-dom)', 'spc2', 'Co-dominant', 'co_dominant', 'Super Specter',    0, NULL, 'Co-dominant version of the Specter pattern morph.', NULL, 2014, 260),
('bp_grail',         'ball_python', 'Grail',            'grl',  'Co-dominant', 'co_dominant', 'Super Grail',      0, NULL, 'Reduces and rearranges pattern into a distinctive grail-like arrangement.', NULL, 2015, 265),
('bp_morphic',       'ball_python', 'Morphic',          'mor',  'Co-dominant', 'co_dominant', 'Super Morphic',    0, NULL, 'Pattern modifier with brightening effect.', NULL, 2014, 270),
('bp_leopard_dom',   'ball_python', 'Leopard (Dominant line)','lepd','Co-dominant','co_dominant','Super Leopard Dom', 0, NULL, 'Dominant/Co-dominant leopard pattern. Spots and fragmented pattern.', NULL, 2010, 275),
('bp_toffee_cod',    'ball_python', 'Toffee (Co-dom)',  'tofc', 'Co-dominant', 'co_dominant', 'Super Toffee',     0, NULL, 'Co-dominant toffee line. Warm brown colour modifier.', NULL, 2010, 280),
('bp_jigsaw',        'ball_python', 'Jigsaw',           'jig',  'Co-dominant', 'co_dominant', 'Super Jigsaw',     0, NULL, 'Produces jigsaw-like pattern fragmentation. Eye-catching and dramatic.', NULL, 2014, 285),
('bp_cryptic_cod',   'ball_python', 'Cryptic (Co-dom)', 'cryc', 'Co-dominant', 'co_dominant', 'Super Cryptic',    0, NULL, 'Co-dominant cryptic. Pattern disruption morph.', NULL, 2013, 290),
('bp_puzzle_cod',    'ball_python', 'Puzzle (Co-dom)',  'puzc', 'Co-dominant', 'co_dominant', 'Super Puzzle',     0, NULL, 'Co-dominant puzzle gene. Breaks up and rearranges pattern into puzzle-shaped pieces.', NULL, 2016, 295),

-- ── DOMINANT MORPHS ───────────────────────────────────────────
('bp_spider_dom',    'ball_python', 'Spider',           'sp2',  'Dominant', 'dominant', NULL, 1, 'Neurological wobble - head tremor and balance issues. The primary Spider gene is dominant. Severity varies individual to individual. Super Spider (homozygous) shows severe, often life-limiting wobble.', 'Webbing pattern, reduced lateral markings, white belly, variable banding. The original and most common Spider. Dominant - one copy produces the visual.', NULL, 1999, 10),
('bp_pinstripe_dom', 'ball_python', 'Pinstripe',        'pin2', 'Dominant', 'dominant', NULL, 0, NULL, 'Dominant pinstripe (some lines). Most pinstripes are co-dominant with a super form.', NULL, 2001, 20),
('bp_disco',         'ball_python', 'Disco',            'dis',  'Dominant', 'dominant', NULL, 0, NULL, 'Fragmented, disco-ball-like pattern. Dominant - one copy produces visual.', NULL, 2010, 30),
('bp_scaleless',     'ball_python', 'Scaleless',        'scl',  'Dominant', 'dominant', NULL, 0, NULL, 'Completely scaleless body and head. Smooth, tactile appearance. Dominant expression but complex genetics.', NULL, 2013, 40);
